# Generated by Django 5.1.5 on 2025-01-14 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mainImage', models.ImageField(blank=True, null=True, upload_to='site_images/main/')),
                ('moreImages', models.ImageField(blank=True, null=True, upload_to='site_images/more/')),
                ('title', models.TextField()),
                ('type', models.TextField()),
                ('quickInfo', models.TextField()),
                ('detail', models.TextField()),
                ('leader', models.CharField(max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
    ]
