# Generated by Django 5.1.5 on 2025-01-14 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('mainapp', '0002_tourist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tourist',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to.', related_name='tourist_set', related_query_name='tourist', to='auth.group'),
        ),
        migrations.AlterField(
            model_name='tourist',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='tourist_set', related_query_name='tourist', to='auth.permission'),
        ),
    ]
