# Generated by Django 5.1.5 on 2025-01-31 06:59

import django.db.models.deletion
import mainapp.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0005_alter_sitedata_mainimage_alter_sitedata_moreimages'),
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mainImage', models.ImageField(storage=mainapp.storage_backend.MainImageStorage(), upload_to='main_images/')),
                ('moreImages', models.ImageField(blank=True, null=True, storage=mainapp.storage_backend.MoreImagesStorage(), upload_to='more_images/')),
                ('videos', models.FileField(blank=True, null=True, storage=mainapp.storage_backend.VideosStorage(), upload_to='videos/')),
                ('community', models.CharField(max_length=255)),
                ('title', models.CharField(max_length=255)),
                ('quickInfo', models.TextField()),
                ('detail', models.TextField(blank=True, null=True)),
                ('address', models.TextField()),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('profilePicture', models.ImageField(storage=mainapp.storage_backend.MainImageStorage(), upload_to='artist_profiles/')),
                ('instrument', models.CharField(max_length=255)),
                ('moreImages', models.ImageField(blank=True, null=True, storage=mainapp.storage_backend.MoreImagesStorage(), upload_to='artist_more_images/')),
                ('videos', models.FileField(blank=True, null=True, storage=mainapp.storage_backend.VideosStorage(), upload_to='videos/')),
                ('detail', models.TextField(blank=True, null=True)),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='artists', to='mainapp.site')),
            ],
        ),
        migrations.AlterField(
            model_name='userfeedback',
            name='site',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainapp.site'),
        ),
        migrations.DeleteModel(
            name='SiteData',
        ),
    ]
