# Generated by Django 5.1.5 on 2025-01-31 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_site_artist_alter_userfeedback_site_delete_sitedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='site',
            old_name='title',
            new_name='groupName',
        ),
    ]
