# Generated by Django 5.1.5 on 2025-01-31 14:52

import django.db.models.deletion
import mainapp.storage_backend
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0007_rename_title_site_groupname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='moreImages',
        ),
        migrations.RemoveField(
            model_name='site',
            name='videos',
        ),
        migrations.CreateModel(
            name='MoreImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(storage=mainapp.storage_backend.MoreImagesStorage(), upload_to='more_images/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='moreImages', to='mainapp.site')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(storage=mainapp.storage_backend.VideosStorage(), upload_to='videos/')),
                ('site', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mainapp.site')),
            ],
        ),
    ]
