# Generated by Django 5.1.5 on 2025-01-31 17:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_remove_site_moreimages_remove_site_videos_moreimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='moreimage',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistMoreImages', to='mainapp.artist'),
        ),
        migrations.AddField(
            model_name='video',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artistVideos', to='mainapp.artist'),
        ),
        migrations.AlterField(
            model_name='moreimage',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moreImages', to='mainapp.site'),
        ),
        migrations.AlterField(
            model_name='video',
            name='site',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='mainapp.site'),
        ),
    ]
