# Generated by Django 5.1.5 on 2025-01-31 17:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0009_moreimage_artist_video_artist_alter_moreimage_site_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artist',
            name='moreImages',
        ),
        migrations.RemoveField(
            model_name='artist',
            name='videos',
        ),
    ]
